name: Create GitHub Project

on:
  workflow_dispatch:

jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq
      - name: Create classic project board if not exists
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          PROJECT_NAME="AI Prompts Project Management"
          API_URL="https://api.github.com/repos/$REPO/projects"
          # List existing classic projects
          RESPONSE=$(curl -s -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.inertia-preview+json" "$API_URL")
          echo "Raw API response: $RESPONSE"
          PROJECT_ID=$(echo "$RESPONSE" | jq -r ".[] | select(.name == \"$PROJECT_NAME\") | .id")
          if [ -z "$PROJECT_ID" ]; then
            echo "Creating classic project board..."
            curl -s -X POST -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.inertia-preview+json" \
              "$API_URL" \
              -d "{\"name\":\"$PROJECT_NAME\",\"body\":\"Automated project board for AI Prompts\"}"
            echo "Project created."
          else
            echo "Project already exists."
          fi
