name: Create GitHub Project

on:
  workflow_dispatch:

jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq
      - name: Create project if not exists
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROJECT_NAME="AI Prompts Project Management"
          echo "Listing projects for this repository:"
          gh project list --repo "$GITHUB_REPOSITORY" --format json > projects.json
          cat projects.json
          PROJECT_EXISTS=$(jq -r ".[] | select(.title == \"$PROJECT_NAME\") | .id" projects.json)
          if [ -z "$PROJECT_EXISTS" ]; then
            gh project create --repo "$GITHUB_REPOSITORY" --title "$PROJECT_NAME" --format board
            echo "Project created."
          else
            echo "Project already exists."
          fi
