name: Create Classic GitHub Project

on:
  workflow_dispatch:

jobs:
  create-classic-project:
    runs-on: ubuntu-latest
    steps:
      - name: Create Classic Project via GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/jrwhetse/ai-prompts/projects \
            -d '{"name": "AI-Prompts-Project", "body": "Classic project for AI prompts management"}'
