name: Create Classic GitHub Project

on:
  workflow_dispatch:

jobs:
  create-classic-project:
    runs-on: ubuntu-latest
    steps:
      - name: Set up jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Create Classic GitHub Project if not exists
        env:
          GH_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
        run: |
          PROJECT_NAME="AI Prompts Project Management"
          ORG="ByLightSDC"
          REPO="AI-test"
          # Check for existing classic projects
          PROJECTS=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$ORG/$REPO/projects")
          PROJECT_ID=$(echo "$PROJECTS" | jq -r ".[] | select(.name == \"$PROJECT_NAME\") | .id")
          if [ -z "$PROJECT_ID" ]; then
            echo "Creating new classic GitHub Project (repo-level)..."
            CREATE_RESPONSE=$(curl -s -X POST -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.inertia-preview+json" \
              -d '{"name": "'$PROJECT_NAME'", "body": "Automated classic project board."}' \
              "https://api.github.com/repos/$ORG/$REPO/projects")
            echo "Create response: $CREATE_RESPONSE"
            ERRORS=$(echo "$CREATE_RESPONSE" | jq -r '.errors | select(. != null)')
            if [ -n "$ERRORS" ] && [ "$ERRORS" != "null" ]; then
              echo "Error(s) from GitHub API: $ERRORS"
              exit 1
            fi
            echo "Classic project created."
          else
            echo "Classic project already exists."
          fi
